### ISSUE TITLE
Issue linking dynamic libraries

### ISSUE THREAD

**Issue by sga001** [alexcrichton/gcc-rs#155]
Hello,

I'm having issues linking to dynamic libraries. Not sure if the problem is with rust's FFI, this crate, my system's gcc, or something else entirely.

 In rust, when I declare the extern block I add 
`#[link(name="libname")] `but I get linking issues. If I instead add `#[link(name="libname", kind="static")]` everything works fine. I created a super simple toy example to show this. I also tested compiling and linking against the dynamic library using g++ as: ` g++ <file.cpp> -l<libname>` and it works fine.

The code is available at: https://github.com/sga001/rust-linking-issue

My gcc/g++ is version 6.3.1. I'm using Arch Linux 4.9.11.  Rustc version 1.18.0-nightly (2bd4b5c6d 2017-04-23).

Thanks!

**Comment by alexcrichton** [comment]
Oh typically you'll want to mange this through the build script rather than the crate itself. It looks like this is related to linking the boost runtime? If the static version can be located but the dynamic version can't that may mean you need an extra `-L` path somewhere, or that the linkage to boost needs to be tweaked.

Can you gist the error messages you're seeing?

**Comment by sga001** [comment]
Here's the gist. 

https://gist.github.com/sga001/c6031a9f4c4756f97cdf025f433fcbbe

Note that this is not just about Boost. I used boost in the toy example because that's a common library. In my actual application this happens with boost, mpfr, gmp, and gomp (basically all libraries that I'm dynamically linking).

Thanks

**Comment by alexcrichton** [comment]
Hm I can't think of a change that'd affect this, but it'd be good to narrow in on the changes!

This looks like it may not be a gcc-rs issue regardless, but rather a configuration or rustc/cargo issue
