### ISSUE TITLE
Rename `Config` type

### ISSUE THREAD

**Issue by brson** [alexcrichton/gcc-rs#189]
This is not all that descriptive a name, though we're not sure what a better name is. I suggest `Builder`. If nothing better comes up, pick that and we'll bikeshed it on the PR.

cc @alexcrichton @sfackler @dtolnay @kimundi @burntsushi bikeshedding.

**Comment by opilar** [comment]
+1 for `Builder`

**Comment by dtolnay** [comment]
I am not a fan of `Builder` because it makes me expect a `build()` method that gives me back some object that I used it to build.

Some alternatives to explore:

- `gcc::Orchestrator`⸻https://en.wikipedia.org/wiki/Orchestration_(computing)
- `gcc::Invocation`⸻like Clang's `clang::CompilerInvocation`
- `gcc::Build`⸻in the noun sense like "build tool", "build automation"

**Comment by alexcrichton** [comment]
`Build` sounds pretty reasonable to me, becuase that's what's happening here anyway!
